//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolTourWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ActivitiesID { get; set; }
        public string ActivityName { get; set; }
        public string WeatherDescription { get; set; }
        public int WeatherID { get; set; }
    
        public virtual Weather Weather { get; set; }
        
    }
}
